module

public import RequestProject.Sec4_Solution.Coeffect.GradedComonad
public import RequestProject.Sec4_Solution.NoneOneTons

/-!
# Section 4: a categorical model in which `⋉` is genuinely partial

We build a concrete model of the coeffect structure of `GradedComonad.lean` over the
none-one-tons semiring `{0, 1, ω}`, in which the partial colax monoidal structure exists for
equation (1) (`1 ⋉ 1 = 1`, otherwise undefined), but cannot be extended to `ω ⋉ ω`.
This is the semantic counterpart of `adj_push_many_not_derivable`: the categorical reading of
the paper's remark — `⋉` is *colax monoidality* of the graded comonad — explains why leaving
`ω ⋉ ω` undefined is not just a syntactic restriction, but is forced in some models of `!`.

**The model.** Fix a commutative monoid `M` of "resource vectors". An object of `Res M` is a
set of vectors (the possible resource usages of a value); there is a (unique) morphism
`A ⟶ B` iff `B ⊆ A`. This is a thin symmetric monoidal category, with tensor the pointwise
sum `A ⊗ B = A + B` and unit `{0}`. The graded modality is

* `D_0 A = {0}` (discarded: no usage),
* `D_1 A = A` (linear use),
* `D_ω A = ⟨A⟩`, the submonoid generated by `A` (any finite number of uses, like `!`).

All the graded comonad, contraction, weakening and lax monoidal maps exist (`resExp`), and
so does the colax map `n_{1,1}` (`resColax`). But, for two independent resources
`a = (1,0)` and `b = (0,1)` in `ℕ × ℕ`, there is no morphism
`D_t (a ⊗ b) ⟶ D_ω a ⊗ D_ω b` for any grade `t` (`res_no_split_many`): the usages of `a` and
`b` inside `D_t (a ⊗ b)` are correlated, while `D_ω a ⊗ D_ω b` allows independent numbers of
uses. Consequently no partial colax structure with `ω ⋉ ω` defined exists in this model
(`res_no_colax_of_many_defined`); in particular the model is not a model of the `[PPROD]` rule
of Section 2's GrCore (`res_not_grcore_colax`). Since every model of GrCore's `[PPROD]` is
a model of the adjusted one (`lnlColaxOfGrCore`), the adjusted calculus has strictly more
models (`adjusted_colax_strictly_more_models`).
-/

@[expose] public section

namespace LinExp

namespace Coeffect

open CategoryTheory MonoidalCategory Pointwise

/-- Objects of the resource model: sets of resource vectors. -/
structure Res (M : Type) where
  /-- The set of possible resource usages. -/
  set : Set M

namespace Res

variable {M : Type}

/-- `A ⟶ B` iff `B ⊆ A`. -/
instance : Preorder (Res M) where
  le A B := B.set ⊆ A.set
  le_refl _ := subset_refl _
  le_trans _ _ _ h₁ h₂ := h₂.trans h₁

lemma le_def (A B : Res M) : A ≤ B ↔ B.set ⊆ A.set := Iff.rfl

/-- An isomorphism of the thin category from an equality of the underlying sets. -/
def isoOfEq {A B : Res M} (h : A.set = B.set) : A ≅ B where
  hom := homOfLE (by rw [le_def, h])
  inv := homOfLE (by rw [le_def, h])

variable [AddCommMonoid M]

/-- The symmetric monoidal structure: pointwise sum of sets, unit `{0}`. -/
instance : MonoidalCategory (Res M) where
  tensorObj A B := ⟨A.set + B.set⟩
  whiskerLeft _ _ _ f := homOfLE (Set.add_subset_add_left (leOfHom f))
  whiskerRight f _ := homOfLE (Set.add_subset_add_right (leOfHom f))
  tensorUnit := ⟨0⟩
  associator _ _ _ := isoOfEq (add_assoc _ _ _)
  leftUnitor _ := isoOfEq (zero_add _)
  rightUnitor _ := isoOfEq (add_zero _)

instance : SymmetricCategory (Res M) where
  braiding _ _ := isoOfEq (add_comm _ _)

@[simp] lemma tensorObj_set (A B : Res M) : (A ⊗ B).set = A.set + B.set := rfl
@[simp] lemma tensorUnit_set : (𝟙_ (Res M)).set = 0 := rfl

end Res

open LNL

variable {M : Type} [AddCommMonoid M]

/-- The graded modality on sets of resource vectors. -/
def dSet : LNL → Set M → Set M
  | .zero, _ => 0
  | .one, A => A
  | .many, A => AddSubmonoid.closure A

lemma dSet_mono (r : LNL) {A B : Set M} (h : A ⊆ B) : dSet r A ⊆ dSet r B := by
  cases r
  · exact subset_refl _
  · exact h
  · exact AddSubmonoid.closure_mono h

lemma zero_mem_dSet_many (A : Set M) : (0 : M) ∈ dSet .many A :=
  (AddSubmonoid.closure A).zero_mem

lemma dSet_subset_many (r : LNL) (A : Set M) : dSet r A ⊆ dSet .many A := by
  cases r
  · simp [dSet]
  · exact AddSubmonoid.subset_closure
  · exact subset_refl _

lemma dSet_add_subset_many (A : Set M) : dSet .many A + dSet .many A ⊆ dSet .many A := by
  rintro _ ⟨x, hx, y, hy, rfl⟩
  exact (AddSubmonoid.closure A).add_mem hx hy

/-- Lax unit: `D_r {0} ⊆ {0}`. -/
lemma dSet_laxUnit (r : LNL) : dSet r (0 : Set M) ⊆ 0 := by
  cases r
  · exact subset_refl _
  · exact subset_refl _
  · show ((AddSubmonoid.closure ({0} : Set M) : AddSubmonoid M) : Set M) ⊆ _
    rw [AddSubmonoid.closure_singleton_zero]
    simp

/-- Comultiplication: `D_r (D_s A) ⊆ D_{r*s} A`. -/
lemma dSet_comult (r s : LNL) (A : Set M) : dSet r (dSet s A) ⊆ dSet (r * s) A := by
  cases r <;> cases s <;> simp only [dSet, mul_def, mul] <;> try exact subset_refl _
  · exact dSet_laxUnit .many
  · exact AddSubmonoid.closure_le.mpr (subset_refl _)

/-- Approximation: `r ⊑ s` implies `D_r A ⊆ D_s A`. -/
lemma dSet_approx {r s : LNL} (h : r ≤ s) (A : Set M) : dSet r A ⊆ dSet s A := by
  rcases h with rfl | rfl
  · exact subset_refl _
  · exact dSet_subset_many r A

/-- Contraction: `D_r A + D_s A ⊆ D_{r+s} A`. -/
lemma dSet_contr (r s : LNL) (A : Set M) : dSet r A + dSet s A ⊆ dSet (r + s) A := by
  have key : dSet r A + dSet s A ⊆ dSet .many A :=
    (Set.add_subset_add (dSet_subset_many r A) (dSet_subset_many s A)).trans
      (dSet_add_subset_many A)
  cases r <;> cases s
  all_goals first
    | exact key
    | (show _ + (0 : Set M) ⊆ _; rw [add_zero]; exact subset_refl _)
    | (show (0 : Set M) + _ ⊆ _; rw [zero_add]; exact subset_refl _)

/-- Lax monoidality: `D_r (A + B) ⊆ D_r A + D_r B`. -/
lemma dSet_lax (r : LNL) (A B : Set M) : dSet r (A + B) ⊆ dSet r A + dSet r B := by
  cases r
  · simp [dSet]
  · exact subset_refl _
  · show ((AddSubmonoid.closure (A + B) : AddSubmonoid M) : Set M) ⊆ _
    rw [show dSet .many A + dSet .many B =
      ((AddSubmonoid.closure A ⊔ AddSubmonoid.closure B : AddSubmonoid M) : Set M) from
      (AddSubmonoid.coe_sup _ _).symm]
    refine AddSubmonoid.closure_le.mpr ?_
    rintro _ ⟨x, hx, y, hy, rfl⟩
    exact AddSubmonoid.add_mem _
      (AddSubmonoid.mem_sup_left (AddSubmonoid.subset_closure hx))
      (AddSubmonoid.mem_sup_right (AddSubmonoid.subset_closure hy))

/-- The graded modality `D_r` as a functor on the resource model. -/
def resD (r : LNL) : Res M ⥤ Res M :=
  Monotone.functor (f := fun A => ⟨dSet r A.set⟩) (fun _ _ h => dSet_mono r h)

@[simp] lemma resD_obj_set (r : LNL) (A : Res M) : ((resD r).obj A).set = dSet r A.set := rfl

/-- A natural transformation between functors into a thin category. -/
def thinNat {F G : Res M ⥤ Res M} (h : ∀ A, (G.obj A).set ⊆ (F.obj A).set) : F ⟶ G where
  app A := homOfLE (h A)
  naturality _ _ _ := Subsingleton.elim _ _

/-- The resource model is an `{0, 1, ω}`-graded exponential comonad. -/
def resExp : GradedExponential LNL (Res M) where
  D := resD
  counit := thinNat (fun _ => subset_refl _)
  comult r s := thinNat (fun A => dSet_comult r s A.set)
  approx h := thinNat (fun A => dSet_approx h A.set)
  counit_comult _ _ := Subsingleton.elim _ _
  comult_counit _ _ := Subsingleton.elim _ _
  comult_assoc _ _ _ _ := Subsingleton.elim _ _
  approx_refl _ := by ext; exact Subsingleton.elim _ _
  approx_trans _ _ := by ext; exact Subsingleton.elim _ _
  weak _ := homOfLE (subset_refl _)
  contr r s A := homOfLE (dSet_contr r s A.set)
  laxUnit r := homOfLE (dSet_laxUnit r)
  lax r A B := homOfLE (dSet_lax r A.set B.set)
  weak_natural _ := Subsingleton.elim _ _
  contr_natural _ _ _ _ _ := Subsingleton.elim _ _
  lax_natural _ _ _ _ _ _ _ := Subsingleton.elim _ _

/-- The underlying graded comonad of the resource model. -/
abbrev resComonad : GradedComonad LNL (Res M) := (resExp (M := M)).toGradedComonad

/-- The resource model has the partial colax monoidal structure of equation (1): the map
`n_{1,1,A,B} : D_1 (A ⊗ B) ⟶ D_1 A ⊗ D_1 B`. So it models the `[PPROD]` rule of the adjusted
calculus over `{0, 1, ω}`. -/
def resColax : HSupColax LNL.hsup (resComonad (M := M)) where
  n {r s t} h A B := homOfLE (by
    obtain ⟨rfl, rfl, rfl⟩ : r = one ∧ s = one ∧ t = one := by
      cases r <;> cases s <;> cases t <;> simp_all [LNL.hsup]
    exact subset_refl _)
  natural _ _ _ _ _ _ _ := Subsingleton.elim _ _
  counit _ _ _ := Subsingleton.elim _ _
  symm _ _ _ _ := Subsingleton.elim _ _
  assoc _ _ _ _ _ _ _ := Subsingleton.elim _ _

/-- The resource model has a semantic `push` at grade `1` (counterpart of `adj_push_one`). -/
theorem res_push_one (A B : Res M) :
    Nonempty ((resComonad.D 1).obj (A ⊗ B) ⟶ (resComonad.D 1).obj A ⊗ (resComonad.D 1).obj B) :=
  ⟨resColax.push (by rfl) A B⟩

/-- The resource `a = (1, 0)`. -/
def resA : Res (ℕ × ℕ) := ⟨{(1, 0)}⟩
/-- The resource `b = (0, 1)`. -/
def resB : Res (ℕ × ℕ) := ⟨{(0, 1)}⟩

/-- **No colax map at `ω ⋉ ω`.** In the resource model there is no morphism
`D_t (a ⊗ b) ⟶ D_ω a ⊗ D_ω b`, for any grade `t`. -/
theorem res_no_split_many (t : LNL) :
    IsEmpty ((resComonad.D t).obj (resA ⊗ resB) ⟶
      (resComonad.D ω).obj resA ⊗ (resComonad.D ω).obj resB) := by
  refine ⟨fun f => ?_⟩
  have hf := (Res.le_def _ _).mp (leOfHom f)
  have hmem : ((1, 0) : ℕ × ℕ) ∈ dSet t ({(1, 0)} + {(0, 1)} : Set (ℕ × ℕ)) := by
    refine hf (a := ((1, 0) : ℕ × ℕ)) ?_
    refine ⟨(1, 0), AddSubmonoid.subset_closure rfl, 0, zero_mem_dSet_many _, by simp⟩
  rw [Set.singleton_add_singleton] at hmem
  cases t
  · simp [dSet] at hmem
  · simp [dSet] at hmem
  · obtain ⟨n, hn⟩ := AddSubmonoid.mem_closure_singleton.mp hmem
    simp only [Prod.smul_mk, smul_eq_mul, Prod.mk_add_mk, Prod.mk.injEq] at hn
    omega

/-- **The partiality of `⋉` is forced in the resource model.** For any partial operation
`hs` on `{0, 1, ω}` in which `ω ⋉ ω` is defined (whatever its value), the resource model
admits no partial colax monoidal structure. -/
theorem res_no_colax_of_many_defined (hs : LNL → LNL → Option LNL) (h : (hs ω ω).isSome) :
    IsEmpty (HSupColax hs (resComonad (M := ℕ × ℕ))) :=
  no_colax_of_no_split (A := resA) (B := resB) res_no_split_many h

/-- In particular the resource model is **not** a model of the `[PPROD]` rule of Section 2's
GrCore (`r ⋉ s` defined iff `r = s`), although it models the adjusted calculus' `[PPROD]`
(`resColax`). -/
theorem res_not_grcore_colax : IsEmpty (HSupColax diagHsup (resComonad (M := ℕ × ℕ))) :=
  res_no_colax_of_many_defined _ (by simp [diagHsup])

/-- Summary of the coeffect reading of Section 4 in the resource model: it carries the
colax structure for equation (1), but none for any `⋉` with `ω ⋉ ω` defined. -/
theorem res_colax_exactly_eq1 :
    Nonempty (HSupColax LNL.hsup (resComonad (M := ℕ × ℕ))) ∧
      ∀ hs : LNL → LNL → Option LNL, (hs ω ω).isSome →
        IsEmpty (HSupColax hs (resComonad (M := ℕ × ℕ))) :=
  ⟨⟨resColax⟩, res_no_colax_of_many_defined⟩

/-- Every model of Section 2's `[PPROD]` (a colax structure for `diagHsup`) is a model of the
adjusted `[PPROD]` over `{0, 1, ω}` (equation (1)), for any graded comonad over `{0, 1, ω}`. -/
def lnlColaxOfGrCore {C : Type} [Category C] [MonoidalCategory C] [BraidedCategory C]
    {G : GradedComonad LNL C} (N : HSupColax diagHsup G) : HSupColax LNL.hsup G :=
  N.restrict (fun {r s t} h => by
    obtain ⟨rfl, rfl, rfl⟩ : r = one ∧ s = one ∧ t = one := by
      cases r <;> cases s <;> cases t <;> simp_all [LNL.hsup]
    simp [diagHsup])

/-- **Semantically, the adjusted calculus has strictly more models than GrCore.** Models of
GrCore's `[PPROD]` are models of the adjusted one (`lnlColaxOfGrCore`), but the resource model
is a model of the adjusted `[PPROD]` and not of GrCore's. -/
theorem adjusted_colax_strictly_more_models :
    (∀ (C : Type) [Category C] [MonoidalCategory C] [BraidedCategory C]
        (G : GradedComonad LNL C), Nonempty (HSupColax diagHsup G) →
          Nonempty (HSupColax LNL.hsup G)) ∧
      Nonempty (HSupColax LNL.hsup (resComonad (M := ℕ × ℕ))) ∧
      IsEmpty (HSupColax diagHsup (resComonad (M := ℕ × ℕ))) :=
  ⟨fun _ _ _ _ _ ⟨N⟩ => ⟨lnlColaxOfGrCore N⟩, ⟨resColax⟩, res_not_grcore_colax⟩

end Coeffect

end LinExp

end
