module

public import RequestProject.Sec4_Solution.Hsup

/-!
# Section 4: the none-one-tons semiring `{0, 1, ω}`

`r + s = r` if `s = 0`, `r + s = s` if `r = 0`, and `ω` otherwise;
`r * 0 = 0 * r = 0`, `r * ω = ω * r = ω` (for `r ≠ 0`), `r * 1 = 1 * r = r`;
the pre-order is generated by `0 ⊑ ω` and `1 ⊑ ω`.

The `hsup` operation is equation (1) of the paper: `1 ⊔ 1 = 1` and `r ⊔ s` is undefined
otherwise.  (This semiring is called `LNL` in Granule, with elements `0`, `1`, `Many`.)
-/

@[expose] public section

namespace LinExp

/-- The none-one-tons semiring `{0, 1, ω}`. -/
inductive LNL : Type where
  | zero
  | one
  | many
  deriving DecidableEq, Repr

namespace LNL

/-- Addition of `{0, 1, ω}`. -/
def add : LNL → LNL → LNL
  | r, zero => r
  | zero, s => s
  | _, _ => many

/-- Multiplication of `{0, 1, ω}`. -/
def mul : LNL → LNL → LNL
  | zero, _ => zero
  | _, zero => zero
  | one, s => s
  | r, one => r
  | many, many => many

instance : Zero LNL := ⟨zero⟩
instance : One LNL := ⟨one⟩
instance : Add LNL := ⟨add⟩
instance : Mul LNL := ⟨mul⟩

instance : CommSemiring LNL where
  add_assoc a b c := by cases a <;> cases b <;> cases c <;> rfl
  zero_add a := by cases a <;> rfl
  add_zero a := by cases a <;> rfl
  add_comm a b := by cases a <;> cases b <;> rfl
  mul_assoc a b c := by cases a <;> cases b <;> cases c <;> rfl
  one_mul a := by cases a <;> rfl
  mul_one a := by cases a <;> rfl
  zero_mul a := by cases a <;> rfl
  mul_zero a := by cases a <;> rfl
  left_distrib a b c := by cases a <;> cases b <;> cases c <;> rfl
  right_distrib a b c := by cases a <;> cases b <;> cases c <;> rfl
  mul_comm a b := by cases a <;> cases b <;> rfl
  nsmul := nsmulRec

/-- The pre-order of `{0, 1, ω}`: `r ⊑ s` iff `r = s` or `s = ω`. -/
instance : Preorder LNL where
  le r s := r = s ∨ s = many
  le_refl r := Or.inl rfl
  le_trans a b c := by
    rintro (rfl | rfl) (rfl | rfl) <;> simp

/-- `ω` -/
scoped notation "ω" => LNL.many

@[simp] lemma zero_def : (0 : LNL) = zero := rfl
@[simp] lemma one_def : (1 : LNL) = one := rfl

lemma add_def (r s : LNL) : r + s = add r s := rfl
lemma mul_def (r s : LNL) : r * s = mul r s := rfl

lemma le_iff (r s : LNL) : r ≤ s ↔ r = s ∨ s = many := Iff.rfl

instance : DecidableRel (α := LNL) (· ≤ ·) := fun r s =>
  decidable_of_iff (r = s ∨ s = many) (le_iff r s).symm

/-- Equation (1): `r ⊔ s` is defined (and equal to `1`) only when `r = s = 1`. -/
def hsup : LNL → LNL → Option LNL
  | one, one => some one
  | _, _ => none

instance : HSup LNL where
  hsup := hsup
  comm r s := by cases r <;> cases s <;> rfl
  assoc r s t := by cases r <;> cases s <;> cases t <;> rfl

lemma hsup_eq_some {r s t : LNL} : HSup.hsup r s = some t ↔ r = one ∧ s = one ∧ t = one := by
  cases r <;> cases s <;> cases t <;> simp [HSup.hsup, hsup]

end LNL

end LinExp

end
